### PR TITLE
Improvement in universal_generator/cpp.toml

### PR DESCRIPTION
**Pull request by naskya**
https://github.com/kyuridenamida/atcoder-tools/pull/229

### CODE REVIEW

**Comment by kyuridenamida** [comment]
TIL GitHub Actions was simply down yesterday. Now you can see some checks got failed. Can you fix that following the error message?

**Comment by naskya** [comment]
Yes. The cause of the failure seems to be a mismatch between the generated code and the prepared code. Can I just manually reflect this change in generated_code.txt(s) in test_codegen directory?

**Comment by kyuridenamida** [comment]
Yeah, you are right. Please update them manually.

**Comment by naskya** [comment]
I updated the prepared code.

**Comment by kyuridenamida** [comment]
Thanks! Going to merge

**Pull request merged**
